
FROM node:8

RUN apt-get update -y && apt-get install -y python3-pip python-dev \
    software-properties-common python3-software-properties \
    x264 x265 ffmpeg && rm -rf /var/lib/apt/lists/*

#Build the frontend

COPY ./frontend/ /usr/src/frontend
WORKDIR /usr/src/frontend
RUN npm install
RUN npm run build

#Build the backend

ENV PYTHONUNBUFFERED 1
COPY ./backend /usr/src/app/
WORKDIR /usr/src/app

RUN pip3 install -r requirements.txt

