# Generated by Django 2.2.3 on 2019-07-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0008_auto_20181224_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='', max_length=300),
        ),
    ]
