# Generated by Django 2.1.2 on 2018-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0004_video_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='codec',
            new_name='video_codec',
        ),
        migrations.AddField(
            model_name='video',
            name='audio_codec',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
