# Generated by Django 2.1.2 on 2018-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0002_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(default='', max_length=100),
        ),
    ]
