# Generated by Django 2.1.2 on 2018-12-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0007_auto_20181224_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='baseurl',
            field=models.CharField(default='', max_length=300),
        ),
    ]
