# Generated by Django 2.2.3 on 2019-07-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0009_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='baseurl',
            new_name='video_url',
        ),
    ]
