# Generated by Django 2.2.3 on 2019-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0010_auto_20190728_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_folder',
            field=models.CharField(default='', max_length=300),
        ),
    ]
