# Generated by Django 2.2.3 on 2019-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0011_video_video_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_folder',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('videos', models.ManyToManyField(to='StreamServerApp.Video')),
            ],
        ),
    ]
