# Generated by Django 2.2.3 on 2019-10-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0013_auto_20190901_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subtitle_url',
            new_name='en_subtitle_url',
        ),
        migrations.AddField(
            model_name='video',
            name='fr_subtitle_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
