# Generated by Django 2.2.8 on 2019-12-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0014_auto_20191019_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ov_subtitle_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
