# Generated by Django 2.2.8 on 2020-02-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0017_series_thumbail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
