# Generated by Django 2.2.8 on 2020-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0020_auto_20200527_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideohistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='episode',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, null=True),
        ),
    ]
