# Generated by Django 2.2.8 on 2020-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0021_auto_20200601_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='en_subtitle_url',
            new_name='en_webvtt_subtitle_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='fr_subtitle_url',
            new_name='fr_webvtt_subtitle_url',
        ),
        migrations.AddField(
            model_name='video',
            name='en_srt_subtitle_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='fr_srt_subtitle_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
