# Generated by Django 2.2.8 on 2020-12-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0021_auto_20200601_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='en_subtitle_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fr_subtitle_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ov_subtitle_url',
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webvtt_subtitle_url', models.CharField(default='', max_length=300)),
                ('webvtt_sync_url', models.CharField(default='', max_length=300)),
                ('srt_path', models.CharField(default='', max_length=300)),
                ('srt_sync_path', models.CharField(default='', max_length=300)),
                ('vtt_path', models.CharField(default='', max_length=300)),
                ('vtt_sync_path', models.CharField(default='', max_length=300)),
                ('language', models.CharField(choices=[('fra', 'French'), ('eng', 'English'), ('OV', 'Original Version')], default='eng', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uploaded_data', models.FileField(default='', upload_to='uploads/')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='StreamServerApp.Video')),
            ],
        ),
    ]
