# Generated by Django 2.2.8 on 2020-07-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0022_auto_20200625_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='en_srt_subtitle_path',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='fr_srt_subtitle_path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
