# Generated by Django 2.2.8 on 2021-06-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0023_auto_20210130_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='episode',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='metadata',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StreamServerApp.Movie'),
        ),
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StreamServerApp.Series'),
        ),
    ]
