# Generated by Django 2.2.8 on 2020-08-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0023_auto_20200716_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='en_srt_subtitle_path',
            new_name='en_srt_sync_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='fr_srt_subtitle_path',
            new_name='fr_srt_sync_url',
        ),
    ]
