# Generated by Django 2.2.8 on 2020-08-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0024_auto_20200804_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='en_webvtt_sync_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='fr_webvtt_sync_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
