# Generated by Django 2.2.8 on 2022-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0024_auto_20210624_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
