# Generated by Django 4.2 on 2024-06-18 09:17

from django.db import migrations
from StreamServerApp.models import Video, Series, Movie, Subtitle
from StreamServerApp.media_management.cover_downloader import cover_downloader
import os

def get_cover(apps, schema_editor):

    if os.getenv('TMBD_KEY'):

        movies = Movie.objects.all()
        for movie in movies:
            movie.video_set
            output_file = "/usr/src/static/{}.jpeg".format(movie.title)
            cover_downloader.download_cover(serie.title, output_file, True)
            
        series = Series.objects.all()
        for serie in series:
            output_file = "/usr/src/static/{}.jpeg".format(serie.title)
            ret = cover_downloader.download_cover(serie.title, output_file, True)
            if ret:
                serie.thumbnail = output_file
                serie.save()






class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0025_video_audio_path'),
    ]

    operations = [
        migrations.RunPython(code=get_cover, reverse_code=migrations.RunPython.noop),
    ]
