# Generated by Django 2.2.8 on 2020-11-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0025_auto_20200805_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webvtt_subtitle_url', models.CharField(default='', max_length=300)),
                ('webvtt_sync_url', models.CharField(default='', max_length=300)),
                ('srt_path', models.CharField(default='', max_length=300)),
                ('srt_sync_path', models.CharField(default='', max_length=300)),
                ('vtt_path', models.CharField(default='', max_length=300)),
                ('vtt_sync_path', models.CharField(default='', max_length=300)),
                ('language', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StreamServerApp.Video')),
            ],
        ),
    ]
