# Generated by Django 2.2.8 on 2020-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0026_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(choices=[('fra', 'French'), ('eng', 'English'), ('OV', 'Original Version')], default='eng', max_length=3),
        ),
    ]
