# Generated by Django 4.2 on 2024-08-30 13:16

from django.db import migrations

from StreamServerApp.models import Video
from StreamServerApp.media_processing import get_size
import os, math

def get_filesize(apps, schema_editor):

        videos = Video.objects.all()
        for video in videos:
            playlistdir = os.path.split(video.video_folder)[0]
            size_in_bytes = get_size(playlistdir)
            size_in_megabytes = math.ceil(float(size_in_bytes) * 0.000001)
            video.video_folder_size_in_MB = size_in_megabytes
            video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0027_video_video_folder_size_in_mb'),
    ]

    operations = [
        migrations.RunPython(code=get_filesize, reverse_code=migrations.RunPython.noop),
    ]
