# Generated by Django 2.2.8 on 2020-11-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0027_auto_20201101_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='en_srt_subtitle_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='en_srt_sync_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='en_webvtt_subtitle_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='en_webvtt_sync_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fr_srt_subtitle_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fr_srt_sync_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fr_webvtt_subtitle_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fr_webvtt_sync_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ov_subtitle_url',
        ),
    ]
