# Generated by Django 2.2.8 on 2020-11-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0028_auto_20201101_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='StreamServerApp.Video'),
        ),
    ]
