# Generated by Django 2.2.8 on 2020-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0029_auto_20201101_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='uploadeddata',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
