name: master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Test Frontend
        run: |
          docker compose -f docker-compose-debug.yml run --rm frontend npm run test
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/Dockerfile.prod
          load: true
          tags: webmultimedia/http-streaming-server:master
      -
        name: Test Backend
        run: |
          cp -r tests/* Videos/ 
          docker compose -f docker-compose-prod.yml run --rm web ./wait-for-it.sh db:5432 -- python3 manage.py test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: webmultimedia/http-streaming-server:master
